// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA_uAYoMY29xJHOoOUFcxP68o43Zq9qcA',
    appId: '1:842518645877:web:07d7591ddafd86de39bc3c',
    messagingSenderId: '842518645877',
    projectId: 'rehab-a0153',
    authDomain: 'rehab-a0153.firebaseapp.com',
    storageBucket: 'rehab-a0153.firebasestorage.app',
    measurementId: 'G-F9EL3CPYDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQyGnbSBDq0Ts7q9fsOaFrru7vdt1G5JE',
    appId: '1:842518645877:android:2abc13f55146a83b39bc3c',
    messagingSenderId: '842518645877',
    projectId: 'rehab-a0153',
    storageBucket: 'rehab-a0153.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9kgEvFdIkDRxONlF-jZ2m2sPZZObH89c',
    appId: '1:842518645877:ios:6f9586953a78b97639bc3c',
    messagingSenderId: '842518645877',
    projectId: 'rehab-a0153',
    storageBucket: 'rehab-a0153.firebasestorage.app',
    iosBundleId: 'com.example.rehab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9kgEvFdIkDRxONlF-jZ2m2sPZZObH89c',
    appId: '1:842518645877:ios:6f9586953a78b97639bc3c',
    messagingSenderId: '842518645877',
    projectId: 'rehab-a0153',
    storageBucket: 'rehab-a0153.firebasestorage.app',
    iosBundleId: 'com.example.rehab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA_uAYoMY29xJHOoOUFcxP68o43Zq9qcA',
    appId: '1:842518645877:web:0e9915c9db95763b39bc3c',
    messagingSenderId: '842518645877',
    projectId: 'rehab-a0153',
    authDomain: 'rehab-a0153.firebaseapp.com',
    storageBucket: 'rehab-a0153.firebasestorage.app',
    measurementId: 'G-999TYLXNDS',
  );
}
